version: '3.8'

services:
  minmax_octopus_bot:
    container_name: MinMaxOctopusBot
    image: markturner/octopus-minmax-bot
    restart: unless-stopped
    environment:
      - TZ=Europe/London
      - ACC_NUMBER=<your_account_number>
      - API_KEY=<your_api_key>
      - EXECUTION_TIME=23:00
      - NOTIFICATION_URLS=<your_apprise_notification_urls>
      - ONE_OFF=false
      - DRY_RUN=false
      - TARIFFS=go,agile,flexible
